### ISSUE TITLE
Not fixed IP for our GPC VM + bubble in github

### ISSUE THREAD

**Issue by audreyviriot** [sid027/dt1-23#3]
I have some questions regarding the assignment 1. 

- To do API calls in my bubble app I'm using the external IP of my GCP VM (ex: http://35.xx.xx.xx:5000/ping). Every time I turn off and on again my VM, the external IP changes. How will it work for the evaluation ? We will need to turn on the machine when you will tell us to do it and adapt the API call in the bubble app to be sure it's working ? Or did I missed something ? 
- In the assignment description, you wrote that our GitHub repository must contains the « Bubble (no)code that interacts with the docker files ». How are we suppose to integrate the frontend in Github ? I linked my Github and bubble account but of what I read so far we don’t have access to the source code and we can’t run bubble app out of the bubble editor, so what are we suppose to put in our GitHub repository for the frontend, the link to our bubble app ?

**Comment by sid027** [comment]
**To do API calls in my bubble app I'm using the external IP of my GCP VM (ex: http://35.xx.xx.xx:5000/ping). Every time I turn off and on again my VM, the external IP changes. How will it work for the evaluation ? We will need to turn on the machine when you will tell us to do it and adapt the API call in the bubble app to be sure it's working ? Or did I missed something ?**
_I would say that after the deadline is over, just leave the VM running. That should solve the problem. Once you get the feedback then you can turn it off._

In the assignment description, you wrote that our GitHub repository must contains the « Bubble (no)code that interacts with the docker files ». How are we suppose to integrate the frontend in Github ? I linked my Github and bubble account but of what I read so far we don’t have access to the source code and we can’t run bubble app out of the bubble editor, so what are we suppose to put in our GitHub repository for the frontend, the link to our bubble app ?
_Let me check the Bubble part again. The language is misleading what I seemed to have written. Just paste the link to the Bubble app you made. This is what I meant. I will make the correction._

Does this help?

**Comment by audreyviriot** [comment]
@sid027 yes thanks a lot, all clear.
