### ISSUE TITLE
Pushing Image to Docker Hub denied

### ISSUE THREAD

**Issue by LT2904** [sid027/dt1-23#5]
Hello Singh Siddhartha and Levent Josh,

hope you are well.

I have a problem with a task of our 1st assignment.

I cannot push the image that I have locally in my Docker into the Docker Hub because I get the following error message (see screenshot).
![Screenshot image push to Docker Hub denied](https://github.com/sid027/dt1-23/assets/145026520/2d67f7c1-14ee-4a8f-a32b-8b17eb867776)

I have already checked the settings in my Docker ("Browserwise" and Desktop), but I don't know what the problem could be... Can you help or do you have a hint?
 

Many thanks in advance and best regards ,

**Comment by sid027** [comment]
There are few things to keep in mind when you want to push the image.
- login to dockerhub from your desktop
- the local docker image name should follow the convention <your dockerhub username>/<local docker image name>
- A repo is created on dockerhub with the same name as above.

I think the second one is your problem. Check here: https://jsta.github.io/r-docker-tutorial/04-Dockerhub.html

Let me know if it still doesn't work.

**Comment by LT2904** [comment]
Hello Sid,

thank you very much for the information.

I will check it and hope that it will work.

BR Lukas

**Comment by HaraShun** [comment]
@LT2904 

I and my friend also ran into the same problem.

However, by giving the Docker image an alias as shown below, we can now push it to Dockerhub.

```
$ dokcer tag f3e62c112981 YOUR_DOCKERHUB_USER_NAME/assignment_lukas_theobald:v1
```

IMAGE_ID is
![image](https://github.com/sid027/dt1-23/assets/2841965/49a0261e-70ac-41e0-86d3-3244e6c0afab)


So, in your case
```
$ dokcer tag IMAGE_ID YOUR_DOCKERHUB_USER_NAME/IMAGE_NAME:TAG
```

I want you to try it !

**Comment by LT2904** [comment]
Hey @HaraShun ,

i solved the problem with Sid instructions, Thank you for letting me know and trying to help, I appreciate it! :)
