### ISSUE TITLE
README content?

### ISSUE THREAD

**Issue by mariaszelecka** [sid027/dt1-23#7]
Hi @joshlevent and @sid027 ,
what exactly do you want to see in the README file?
name of our private github repository
External IP Address
firewall details?

Thanks

**Comment by sid027** [comment]
https://teams.microsoft.com/l/message/19:bc52c3e9303d4300bc55f78711c5c7d1@thread.tacv2/1699973106723?tenantId=d6a1cf8c-768e-4187-a738-b6e50c4deb4a&groupId=126d4499-0bdb-45d2-abc8-755ffd7faac8&parentMessageId=1699973106723&teamName=Master%20Digital%20BA%20-%20DIGI23&channelName=DT1%20Enabling%20Technologies&createdTime=1699973106723&allowXTenantAccess=false

**Comment by joshlevent** [comment]
For completeness, what is written at the link is follows:

> Make sure you have all the technical specifications in the README - architecture, IP of the backend, port, bubble link etc. Other details of what you did is upto you - however you feel like expressing it. There is not "correct length" of your README file requirement - just make sure I can understand everything you did or didn't do.
