### ISSUE TITLE
Firewall rules for Bubble

### ISSUE THREAD

**Issue by yannicktt16** [sid027/dt1-23#8]
Hello @sid027 & @joshlevent 
I have two quick questions:

- Could you provide the IP-Adress we need to use to grant access to our GCP? (which type of access do you need? SSH / Everything/ only Port 5000)?

- My Bubble.io app now is able to make requests via my proxy server. However, I would like to implement rather strickt rules to my fireqall and therefore block anything that is not coming from certain IP's. However, this raises the issue that my Bubble.io App is no longer working.
How can I allow requests from my bubble.io application on my firewall? (this is an issue since my application has no fixed IP).

Thanks in advance for your answers. :)
Best regards
Yannick

**Comment by sid027** [comment]
> Hello @sid027 & @joshlevent I have two quick questions:
> 
> * Could you provide the IP-Adress we need to use to grant access to our GCP? (which type of access do you need? SSH / Everything/ only Port 5000)?
Will provide it shortly.

> * My Bubble.io app now is able to make requests via my proxy server. However, I would like to implement rather strickt rules to my fireqall and therefore block anything that is not coming from certain IP's. However, this raises the issue that my Bubble.io App is no longer working.
>   How can I allow requests from my bubble.io application on my firewall? (this is an issue since my application has no fixed IP).
For this you will need to know the IP of your Bubble app and allow that in your firewall. Since the bubble app in not actually hosted on your machine, providing your machine IP will not actually work I think!
> 
> Thanks in advance for your answers. :) Best regards Yannick

**Comment by sonjahuber1** [comment]
Hello @sid027 , i have the same question about the firewall, since it looks like Bubble app has no fixed IP, therefore to make the app work it is not really possible to apply strict Firewall rules on the VM. Am I wrong?

**Comment by e-kartofel** [comment]
Hi @sid027, 

One Back-end requirement says: Security settings don’t allow anyone except **required users** to access the backend

I understand from the type of application that the words **required users** are referring exclusively to the front end (the bubble app), and it must be not possible to access to the back-end by any other means than using this app.

As stated, the Bubble app is not running on our servers, and its IP address is not fixed. Then, how can we fulfill this requirement?
I have currently investigated the following:
-  only allow access to the Flask app's port (e.g., 500) from known IPs (this is done), but anyone using this port could access to the back end.
- Implement Cloud Storage authentication (https://cloud.google.com/storage/docs/authentication)

**Comment by yannicktt16** [comment]
Hi @sid027 & @joshlevent 

Thanks for your help.
I did extensive testing with my colleagues and it actually does seem that the bubble.io preview runs locally on your device. So the management of the IP should be possible for the devices. So this issue is solved.

I would like to ask you again to provide the information about your IP-Adress and what rights you would need to access our application. We also have other tasks and I would like to finish the DT1 assignment as soon as possible.
Therefore, I would really appreciate if you can provide the needed information.

Thanks again and best regards
Yannick

**Comment by sid027** [comment]
https://teams.microsoft.com/l/message/19:bc52c3e9303d4300bc55f78711c5c7d1@thread.tacv2/1699973106723?tenantId=d6a1cf8c-768e-4187-a738-b6e50c4deb4a&groupId=126d4499-0bdb-45d2-abc8-755ffd7faac8&parentMessageId=1699973106723&teamName=Master%20Digital%20BA%20-%20DIGI23&channelName=DT1%20Enabling%20Technologies&createdTime=1699973106723&allowXTenantAccess=false
